name: LeetCode Badges Update

on:
  schedule:
    - cron: "0 0 * * *"   # daily
  workflow_dispatch:

jobs:
  update-leetcode:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download LeetCode Badge
        run: |
          curl -L \
          -H "Accept: image/svg+xml" \
          "https://leetcode-stats.vercel.app/api?username=YOUR_LEETCODE_USERNAME&theme=dark" \
          -o leetcode-badge.svg

      - name: Verify file is SVG
        run: |
          head leetcode-badge.svg

      - name: Commit and Push
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add leetcode-badge.svg
          git diff --quiet && git diff --staged --quiet || git commit -m "Update LeetCode badge"
          git push
