name: GitHub Languages

on:
  schedule:
    - cron: "0 2 * * *"   # daily update
  workflow_dispatch:

permissions:
  contents: write

jobs:
  languages:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          filename: metrics-languages.svg
          base: ""

          # ğŸˆ·ï¸ Languages plugin
          plugin_languages: yes
          plugin_languages_limit: 8
          plugin_languages_threshold: 1%
          plugin_languages_other: yes
